### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by Vokuar** [MarioMasta64/EverythingPortable#10]
Download location is wrong so i edited it and the file name to move is wrong i changed that and it keeps crashing good work tho

**Comment by MarioMasta64** [comment]
skype is discontinued for msi soon. move to discord lol. but. if you can provide me info that can help it would be more useful.

**Comment by Vokuar** [comment]
so i edited the file where i saw the msi file to the lastest exe i could find it downloaded it and it downloaded fine but i couldnt find where it moves the file as i needed to change the file name there too i assume so i think it would work with a little more tinkering idk tho as ive never done this before

**Comment by MarioMasta64** [comment]
you could just give me the link to the latest msi and i can update it

**Comment by MarioMasta64** [comment]
btw it has to be .msi, .exe is a different filetype and grabs the .msi to install

**Comment by MarioMasta64** [comment]
so heres the deal, skype msi is dead
heres where the latest msi would be: https://download.skype.com/msi/SkypeSetup_8.21.0.10.msi
and heres the alternate redirect page for latest msi: http://www.skype.com/go/getskype-msi

however this exists: https://portableapps.com/apps/internet/sportable
