### ISSUE TITLE
is this a super compressed exe file??

### ISSUE THREAD

**Issue by akehsanz** [MarioMasta64/EverythingPortable#15]
hey hello'
not getting assurance of your apps from anywhere in the net...
pls be honest..give me feedbacks...
is this a super compressed exe file with all those apps??
or just connected with som backend servers to download those??

thanks

**Comment by MarioMasta64** [comment]
its just a nsis file containing the launcher that grabs files from this repo / wget you can use 7zip to open it, its just so wget can be included the nsis source file is also extracted on install, everything else is a .bat file and plaintext.
