### ISSUE TITLE
SteamPortable no longer downloading

### ISSUE THREAD

**Issue by EricWu91** [MarioMasta64/EverythingPortable#18]
Not sure if this project is still alive; I installed the EP.exe, and it opened a console; 
Selecting 1) download  a program opens a window which requires me to type the "launcher to download". 
Typing "Steam" redirects to a Selection Time screen, which then prompts me to type "1 - Download Launcher".
Then, this happens: 
![image](https://user-images.githubusercontent.com/9344516/73294778-37efcc80-41e5-11ea-9062-206516bfad1b.png)
(it says the default "Press any key to continue" message).

What do I do?

**Comment by MarioMasta64** [comment]
project abandoned indefinitely thx :)

**Comment by javaScriptCoder-7** [comment]
thanks so much for making this. hope whatever and wherever you are in life now that you continue to do cool stuff like this.

**Comment by MarioMasta64** [comment]
update: 1 year later and its now fixed 👍
