### ISSUE TITLE
smol GUI: enhancement

### ISSUE THREAD

**Issue by vivv3782** [MarioMasta64/EverythingPortable#21]
This is an absolutely amazing project and I enjoy it thus far. I think adding a simple GUI would enhance the project, however.

**Comment by MarioMasta64** [comment]
use portableapps then itll do everything mine does and better along with your gui you want

heres a [link](https://portableapps.com/) and if you want software not available in the project you can simply google "*software name* .paf.exe"

**Comment by MarioMasta64** [comment]
please also see the updated readme for my thoughts on it.
