### ISSUE TITLE
steam doesn't work

### ISSUE THREAD

**Issue by cajlo** [MarioMasta64/EverythingPortable#22]
Hello, I used your project first time today, so may be it is a problem on my side due to not understand how to use it, but...
1) Downloaded "launch_everything.bat", there is no option to use steam, I saw Minecraft, skype, and 66 others, but there wasn't steam (but update all found "launch_steam.bat" and even updated it)
2) Downloaded "launch_steam.bat", installed it, reinstalled it, installed dll's, checked updates of script, checked updates of steam... Steam is downloaded and moved to extra folder - but launch steam do nothing =\ What shell I do?

**Comment by cajlo** [comment]
I've unpacked SteamSetup.exe via 7z, in a "steam" folder, and then moved it "steam" folder to bin location (found it launch_steam.bat what is missing), and after it is working now, I don't know is it a good way to solve problem, but it seems to be working well

**Comment by MarioMasta64** [comment]
cannot reproduce it works perfectly fine for me i did this in a vm with nothing but the single launcher

did you use the d command to install steam it does exactly the steps you stated and works for me

and in the main launcher did you use the command to download launchers

note: if the steam launcher is already there it wont show in this list (as seen here)
![image](https://user-images.githubusercontent.com/20806802/160768012-cac95d1d-3ffa-4322-a27b-6cad2d9e35ac.png)

**Comment by MarioMasta64** [comment]
it is possible that your school or wherever you are may block sourceforge or some of the other resources used

tho its strange they do this and not steam

**Comment by MarioMasta64** [comment]
for steam the resources used are:
[https://eternallybored.org/misc/wget/current/wget.exe](https://eternallybored.org/misc/wget/current/wget.exe) (wget to download anything)
[https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe](https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe) (steam setup)
[https://www.7-zip.org/a/7z1900.msi](https://www.7-zip.org/a/7z1900.msi) (7zip installer)
[https://github.com/activescott/lessmsi/releases/latest](https://github.com/activescott/lessmsi/releases/latest) (lessmsi to extract 7zip installer)

**Comment by MarioMasta64** [comment]
check in the same enviroment you used before that all these are accessible and are not blocked by any type of antivirus program
