### ISSUE TITLE
ProtonVPN

### ISSUE THREAD

**Issue by DewDropTales** [MarioMasta64/EverythingPortable#25]
Hey I was hoping if you could somhow add protonVPN to the program so I can install it without admin rights?

**Comment by MarioMasta64** [comment]
the vpn itself would need drivers to run system wide however theres an extension for firefox and other browers that lets you route traffic through it its also nothing that i can access with my current knowledge as most things ive tried didnt work for extracting the installer (i am not the type to repackage software but to extract as is)
