### ISSUE TITLE
Epic games launcher is broken.

### ISSUE THREAD

**Issue by Baggette** [MarioMasta64/EverythingPortable#27]
it seems to download everything fine although doesn't seem to do anything upon trying to launch it (yes I ran it as admin)

**Comment by Baggette** [comment]
if theres any more info I can provide let me know

**Comment by Baggette** [comment]
oh the issue seemed to be that it didn't copy the files from the EpicGamesLauncherInstaller/SourceDir/Epic Games/Launcher to the bin/epic_games folder

**Comment by MarioMasta64** [comment]
dont run the batch script as admin it breaks 7zip, when epic games asks for admin on its first launch thats when you give it admin.

i have just tested and confimed its still working so im assuming you ran into ^ that issue

![image](https://github.com/MarioMasta64/EverythingPortable/assets/20806802/7fce436d-31ae-4cb4-ab87-03f655b409c7)


basically when epic games asks for admin for launcher prerequisites thats when you say yes to admin not running the batch script as admin

**Comment by Baggette** [comment]
> dont run the batch script as admin it breaks 7zip, when epic games asks for admin on its first launch thats when you give it admin.
> 
> i have just tested and confimed its still working so im assuming you ran into ^ that issue
> 
> ![image](https://user-images.githubusercontent.com/20806802/242915870-7fce436d-31ae-4cb4-ab87-03f655b409c7.png)
> 
> basically when epic games asks for admin for launcher prerequisites thats when you say yes to admin not running the batch script as admin

cool I thought this was a bit dead, thanks for responding

**Comment by MarioMasta64** [comment]
well it is but yea np

**Comment by MarioMasta64** [comment]
[https://github.com/MarioMasta64/EverythingPortable/issues/14](https://github.com/MarioMasta64/EverythingPortable/issues/14)

as referenced here alot of things are just plain broken ^ and more will likely be broken over time
