### ISSUE TITLE
windows update KB5012170 locked my drive so now im blaming the repo owner

### ISSUE THREAD

**Issue by MissNice2** [MarioMasta64/EverythingPortable#28]
I downloaded this happy I could now have Steam but, I kept it on my desktop and I had to restart my PC.(I had a new app update) When I came back into my PC I found Bitlocker pulled up and it was asking for a recovery key. I went on a search spree and found out that, this had given my PC malware and locked my drive. Can you please help with the issue and explain why it did that? Thank you!

**Comment by MissNice2** [comment]
*I'm on Windows 11 and I kept it on my (C:\) Drive*

**Comment by ThePlayerNS** [comment]
Here is a video link that could help you! If it doesn't help, you have to wipe you drive and set up your PC again. Sorry for the bad news. **please do not respond** (video link:  https://www.youtube.com/watch?v=oifhQB-TH9E&t=78s)

**Comment by ghost** [comment]
Keep this in mind next time after you suspect malware before restarting the PC https://youtu.be/CHtZ9-9ch2w

**Comment by MarioMasta64** [comment]
this is actually not a problem with the script unfortunately its a problem where a windows update thats entirely unrelated to the script

more info: [https://petri.com/microsoft-bitlocker-issues-windows-11/](https://petri.com/microsoft-bitlocker-issues-windows-11/)

**Comment by MarioMasta64** [comment]
also this aside literally everything thats done is written in plain text i dont repackage anything or anything i just do it all in realtime which is why things like mine can break very easily and is only meant to be more of a hobby project moreso
