### ISSUE TITLE
Portable Visual C++ Redistributable?

### ISSUE THREAD

**Issue by MrCoolAndroid** [MarioMasta64/EverythingPortable#29]
Steam portable works great, I can download and install games and see them, but whenever I try to launch them it tries to install VC Redistributable on the computer, is it possible to install it on the portable directory or something to Steam to detect it?

**Comment by MarioMasta64** [comment]
thats already an option called download dll's

**Comment by MarioMasta64** [comment]
also its an option in the menu.. please read before leaving issues
![image](https://github.com/MarioMasta64/EverythingPortable/assets/20806802/1918572a-1c4b-496a-a44d-3a7e564ab29e)
