### ISSUE TITLE
misunderstand how your script works and trying to correct you

### ISSUE THREAD

**Issue by RaXorX** [MarioMasta64/EverythingPortable#32]
`if "%~1" neq "" (call :%~1 & exit /b !current_version!)
`
this statement doesn't work properly if it's at the start of the batch file. In my case, it works only if it's before :Menu or after all the other necessary call statements have been run. 

```
call :v30UpgradeCheck

if "%~1" neq "" (call :%~1 & exit /b !current_version!)

:Menu
```

**Comment by MarioMasta64** [comment]
you dont understand how this works do you... its meant to be called from another script (and works perfectly as intended) not from inside the script itself, "%~1" means first parameter (exa: "launch_helpers.bat param1")
