### ISSUE TITLE
Broken PC (windows update broke my pc)

### ISSUE THREAD

**Issue by ThePlayerNS** [MarioMasta64/EverythingPortable#33]
I had this file on my local disc C until I got my USB drive a few days later. I know, it was a dumb idea. I went to check if the program was working, and it was. The problem was have is that it made my file explorer look, weird, to say lightly. Some files were blue named and some couldn't be opened. I restarted my PC in the hopes this problem would go away but, more had showed up. The BitLocker had turned on and I couldn't boot into Windows 11 without the BitLocker Recovery Key. I didn't have that so I searched for a way to fix it. I had no Microsoft account on my PC so, I had to reinstall Windows. Can You tell me why it did this? I'm not mad since all my stuff was backed online, I just don't want this problem to other people.

**Comment by MarioMasta64** [comment]
not a problem with my script blame [windows update](https://www.google.com/search?q=bitlocker+broken+after+windows+update&sca_esv=736f63000bad8be2&sxsrf=ACQVn0-TLFZmTpYHgLcgllD-bD2Z7emA6g%3A1707422446520&source=hp&ei=7jLFZfLsHfLQkPIPgcu_0AY&oq=bitlocker+broken+after+windows+update&gs_lp=EhFtb2JpbGUtZ3dzLXdpei1ocCIlYml0bG9ja2VyIGJyb2tlbiBhZnRlciB3aW5kb3dzIHVwZGF0ZTIEECMYJzIFECEYoAEyBRAhGKABMgUQIRigATIGEAAYFhgeMgsQABiABBiKBRiGAzILEAAYgAQYigUYhgMyCxAAGIAEGIoFGIYDSIcSUJoHWJoHcAF4AJABAJgBhAKgAYQCqgEDMi0xuAEDyAEA-AEC-AEBqAIPwgIHECMY6gIYJw&sclient=mobile-gws-wiz-hp)
