### ISSUE TITLE
how to use steam

### ISSUE THREAD

**Issue by bsl3** [MarioMasta64/EverythingPortable#34]
I cant figuire out for the life of me how to use the steam.bat thingy mcbob. I put in the everything portable folder, I opened it. And I put in "D" to install it, but nothing happens. PLZ HELP)

**Comment by MarioMasta64** [comment]
please check that you are able to access the following url's:

[https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe](https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe)

[https://api.github.com/repos/activescott/lessmsi/releases/latest](https://api.github.com/repos/activescott/lessmsi/releases/latest)

[https://www.7-zip.org/a/7z1900.msi](https://www.7-zip.org/a/7z1900.msi)

[https://raw.githubusercontent.com/MarioMasta64/EverythingPortable/master/launch_helpers.bat](https://raw.githubusercontent.com/MarioMasta64/EverythingPortable/master/launch_helpers.bat)

[https://eternallybored.org/misc/wget/current/wget.exe](https://eternallybored.org/misc/wget/current/wget.exe)

also after using :d you use :2 to actually launch it ( install only needs to be done once :2 can be used from then on )

reopen if need
