### ISSUE TITLE
improving the file structure

### ISSUE THREAD

**Issue by eltrevii** [MarioMasta64/EverythingPortable#37]
hi, i would like to show you how i make these kinds of scripts, i dont do it often but i think this is a better way of doing it:

- launcher.bat: self-explanatory
- modules (name it whatever you want): contains the scripts that have code that could be run more than once
- modules/main.bat: has the code that will ALWAYS be run regardless of the file, e.g. the menus and stuff, the variables can go anywhere else
- modules/updater.bat: you could need this one for some specific program

you can add more modules but i will keep it short for this example
you can run scripts from modules with `call modules/module.bat`

**Comment by MarioMasta64** [comment]
please go back to web developement and do not give things weird names here

**Comment by MarioMasta64** [comment]
also this isnt some npm or python project things dont just update like the reused code that *should* be reused is in launch helpers anything thats not isnt for one reason or another

**Comment by eltrevii** [comment]
ok
