### ISSUE TITLE
unable to use/install epic games

### ISSUE THREAD

**Issue by kirbymybae** [MarioMasta64/EverythingPortable#38]
installing epic games launcher asks you to "please install epic games first". after using lessmsi to see if something would change i realized its probably because the .msi file literally just extracts another installer.

**Comment by MarioMasta64** [comment]
the script already uses lessmsi (and it makes sure to use the latest one with every attemp for extraction) you can see this yourself in .\bin\ this is intended behavior you dont install the exe and it doesnt use whatever is on the system either it makes its own install

you do realize you have to use the D option (as the launcher says to do but you dont read that part)
![image](https://github.com/user-attachments/assets/4c3e3fa1-3314-4dbb-a41a-65a6a616e634)

works for me
![image](https://github.com/user-attachments/assets/e35c6ab2-2fbe-4479-baa3-ece18cd194ca)

on first launch
![image](https://github.com/user-attachments/assets/6fe3b9ee-bb84-4b5e-bd21-4347b20cfac9)

reopen issue if there is actually a problem
