### ISSUE TITLE
Osu! Portable?

### ISSUE THREAD

**Issue by Surg-Dev** [MarioMasta64/EverythingPortable#4]
Is it possible to make a working osu! Portable?

**Comment by MarioMasta64** [comment]
osu is already portable, click change location in osu installer.

**Comment by MarioMasta64** [comment]
so technically yes but due to having no client hash it can not login
![image](https://user-images.githubusercontent.com/20806802/150294659-844ccea6-3eda-4596-ad0b-24564b165b95.png)

**Comment by MarioMasta64** [comment]
it seems that this may have been an edge-case i was able to login just now
