### ISSUE TITLE
OBS Latest

### ISSUE THREAD

**Issue by YouAreTheOneNeo** [MarioMasta64/EverythingPortable#6]
Currently the OBS Latest release is a MacOS hotfix, so the .zip file downloaded is obs-mac-21.0.3-installer.zip

**Comment by MarioMasta64** [comment]
yea, i know its broken. i am lazy sometimes but will fix it when i have the energy.

**Comment by MarioMasta64** [comment]
oh, so it is not my fault, good ^^" however uh, there is no simple way to fix this unfortunately.

**Comment by MarioMasta64** [comment]
oh btw update: this was fixed im not sure how long ago but yea
