### ISSUE TITLE
Nothing seems to be working at the moment

### ISSUE THREAD

**Issue by JustAnIDNumber** [MarioMasta64/EverythingPortable#7]
Any of the options I select will not work, most give a vague "an error has occurred" while other errors state it missing version.txt or a problem with github. Bummer...
![untitled](https://user-images.githubusercontent.com/35935322/37886695-de00499c-308a-11e8-93be-8a8b14379f1a.png)

The option that works is the "Download Everything" which does work but then Steam hangs on "extracting packages"
![untitled](https://user-images.githubusercontent.com/35935322/37886824-c7180fa2-308b-11e8-8d85-eac963f7b3f9.png)

It then proceeds to crash my file explorer by using 100% of the CPU....

**Comment by MarioMasta64** [comment]
the exe installer is provided because wget is not downloading properly (probs got an au blacklisted tbh) and the steam issue is not my problem but with steam, i only redirect appdata.
