### ISSUE TITLE
GMS2 Portable?

### ISSUE THREAD

**Issue by Surg-Dev** [MarioMasta64/EverythingPortable#8]
This will probably be my last request... Gamemaker Studio 1 is portable, apparently, but GMS2 is not... would it be possible to put the installer/software on everything portable (somewhat like vscode?)

Thanks,
-Sam

**Comment by MarioMasta64** [comment]
1. its paid so youd have to buy it for me for me to figure that out.
2. https://store.steampowered.com/app/585410/GameMaker_Studio_2_Desktop/ just install it in steam portable :)

**Comment by Surg-Dev** [comment]
1. It's not paid, you can still install the IDE and use the trial version just fine. All it needs to do is connect to the internet to allow you the full version.
2. You _have_ to buy it through steam if you want to download through steam, believe me I've tried.

**Comment by MarioMasta64** [comment]
ill look into it.

**Comment by Surg-Dev** [comment]
Thanks! Truly means a lot to me. I love your portable work :)

**Comment by MarioMasta64** [comment]
easy .^. 
![image](https://user-images.githubusercontent.com/20806802/39103801-0d0566e0-467b-11e8-8444-866d2ae8b712.png)

expect release soon (will require manually opening browser for download btw)

**Comment by MarioMasta64** [comment]
https://github.com/MarioMasta64/EverythingPortable/blob/master/launch_game_maker_studio_2_poc.bat

**Comment by Surg-Dev** [comment]
_2 days?!_ Thanks!

**Comment by MarioMasta64** [comment]
lol, it could've been 5 minutes for this one. im just lazy :P

**Comment by Neston64** [comment]
@MarioMasta64 hey dude, its possible for you send me the Game Maker portable 2? I really need too :/

**Comment by MarioMasta64** [comment]
its literally in the project already please actually use the project before saying anything..

https://github.com/MarioMasta64/EverythingPortable/blob/master/launch_game_maker_studio_2.bat

**Comment by Neston64** [comment]
My bad, my computer got some bugs and was not showing the old messages.
